name: Bug Report
description: Report problems with code, data or documentation.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out this form to help us reproduce and fix the problem.
  - type: input
    id: title
    attributes:
      label: Title
      description: Short title summarizing the bug
      placeholder: e.g., Notebook fails to run due to missing column
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug.  What happened and what did you expect to happen?
      placeholder: Explain what went wrong.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Run ...
        3. Error occurs
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide any relevant environment details (operating system, Python version, etc.).
      placeholder: e.g., macOS 12.7, Python 3.10, Jupyter Notebook 6.x
    validations:
      required: false
